version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app 
    environment:
      - FLASK_ENV=development  # Optional: Set Flask to development mode for auto-reload
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
